import { ShieldCheck, Network, Headset, Cloud, Server, DatabaseBackup, Monitor, BriefcaseBusiness, type LucideIcon } from "lucide-react";
export type Service = { slug:string; title:string; short:string; description:string; icon:LucideIcon; points:string[]; outcome:string };
export const services: Service[] = [
 {slug:"it-support-maintenance",title:"IT Support & Maintenance",short:"Responsive technical support that keeps your people productive and your business moving.",description:"From everyday troubleshooting to proactive maintenance, we provide dependable IT support tailored to the way your organisation works. Get practical help when you need it, with a focus on preventing disruption before it starts.",icon:Headset,points:["Remote and on-site technical support","Desktop, laptop and software troubleshooting","Preventive maintenance and health checks","Annual maintenance contracts (AMC)","IT asset and issue management"],outcome:"A more reliable workplace, fewer avoidable interruptions and a clear point of contact for IT."},
 {slug:"network-wifi-solutions",title:"Network & Wi-Fi Solutions",short:"Secure, reliable connectivity designed around your workplace and your team.",description:"We design, deploy and manage business networks that support smooth day-to-day operations. From structured network configuration to dependable Wi-Fi coverage, every solution is planned for performance, security and room to grow.",icon:Network,points:["Business LAN and Wi-Fi installation","Router, switch and access point configuration","Network performance and coverage optimisation","Network monitoring and troubleshooting","Secure guest and staff network segmentation"],outcome:"Consistent connectivity and a network foundation that can scale with your business."},
 {slug:"cybersecurity-solutions",title:"Cybersecurity Solutions",short:"Practical protection for your devices, users, business data and digital operations.",description:"Build a stronger security posture with layered protection and practical guidance. We help businesses reduce common risks, improve visibility and establish sensible safeguards across endpoints, email and network infrastructure.",icon:ShieldCheck,points:["Firewall setup and configuration","Endpoint protection deployment","Business email security","IT security assessments","Security best-practice guidance"],outcome:"Better visibility into risk and a more resilient environment for your business."},
 {slug:"cloud-microsoft-365",title:"Cloud & Microsoft 365 Services",short:"Make collaboration simpler with well-managed cloud tools and business email.",description:"Move to modern, connected ways of working with Microsoft 365 and cloud services configured around your organisation. We support setup, migration and ongoing administration to help your team work securely from wherever business happens.",icon:Cloud,points:["Microsoft 365 deployment and configuration","Business email setup and migration","Cloud data and workload migration","User, licence and access administration","Ongoing Microsoft 365 support"],outcome:"A connected, collaborative workplace with cloud services that are properly managed."},
 {slug:"server-it-infrastructure",title:"Server & IT Infrastructure",short:"A stable, well-planned infrastructure for the systems your business depends on.",description:"We help plan, implement and maintain the core infrastructure behind your operations. Whether you are setting up a new server environment or modernising existing systems, we focus on stability, manageability and future readiness.",icon:Server,points:["Server installation and configuration","Virtualisation planning and deployment","Infrastructure management and upgrades","System health and performance checks","Infrastructure documentation and support"],outcome:"An organised and dependable infrastructure built around your operational needs."},
 {slug:"data-backup-recovery",title:"Data Backup & Recovery",short:"Protect business-critical information with planned backup and recovery solutions.",description:"A clear backup strategy helps your business prepare for accidental deletion, hardware failure and unexpected disruption. We implement practical backup routines and recovery planning so your data has a path back when it matters.",icon:DatabaseBackup,points:["Automated backup solution setup","Backup monitoring and verification","Data recovery assistance","Disaster recovery planning","Retention and recovery policy guidance"],outcome:"Greater confidence that important business information can be restored when required."},
 {slug:"it-equipment-supply-installation",title:"IT Equipment Supply & Installation",short:"The right workplace technology, supplied, configured and ready to use.",description:"Simplify IT procurement and deployment with a single partner for equipment supply and installation. We help identify suitable devices and peripherals, then configure and set them up for your team's requirements.",icon:Monitor,points:["Desktop and laptop supply","Server and printer procurement","Networking equipment supply","Device configuration and deployment","Workstation setup and handover"],outcome:"A smoother equipment rollout with devices configured for your working environment."},
 {slug:"it-consulting-office-setup",title:"IT Consulting & Office Setup",short:"Plan your technology with clarity, from the first office layout to the final connection.",description:"Starting a new office or relocating an existing team? We help translate business requirements into a practical IT plan, coordinate the technology setup and prepare your workplace for day one.",icon:BriefcaseBusiness,points:["Technology consulting and IT planning","New office IT setup","Office relocation and IT coordination","Infrastructure and equipment planning","Technology recommendations and roadmaps"],outcome:"A thoughtfully planned workplace where technology is ready to support your team."}
];
export const industries=["Professional Services","Healthcare & Clinics","Education & Training","Retail & E-commerce","Manufacturing & Logistics","Corporate & Multi-office Businesses"];
